<?php
$allTasks = $this->allTasks;

if (isset($allTasks)) : ?>

<div class="w-2/3 mx-auto">
<div class="w-full text-center mt-2">
    <h2 class="text-2xl font-semibold text-center text-orange-400">TASK LIST</h2>
</div>
<br>

<div class="min-w-full">

<?php


?>


    <?php foreach ($allTasks as $task) :
        $shortenedText = isset($task['task_details']) ? substr($task['task_details'], 0, 20) : '';

        $today = new DateTime(); 
        $deadline = new DateTime($task['task_deadline']); 

        // Calcula la diferencia entre las fechas
        $interval = $today->diff($deadline);

        // Obtiene la diferencia en días
        $daysDifference = $interval->days;

        if ($daysDifference == 0) {
            // Hoy
            $daysToDeadline =  '<label class="bg-black-200 block  text-red-500 font-bold" w-1/5 ml-40 text-center>' . $task['task_status'] . '</label>';
        } elseif ($daysDifference > 0 && $daysDifference <= 5) {
            // Quedan menos de 5 días
            $daysToDeadline = '<label class="block  text-yellow-500 font-bold" w-1/5 ml-40 text-center>' . $task['task_status'] . '</label>'; 
        } else {
            // Más de 5 días
            $daysToDeadline = '<label class="block  text-green-500 font-bold" w-1/5 ml-40 text-center>' . $task['task_status'] . '</label>';
        }
    ?>

    <div class="border border-black rounded-md p-2 mb-2">
        <div class="flex mb-2">

            <div class="w-1/5 ml-2 bg-orange-200 rounded-md p-1 text-center">
                <label class="font-bold">Created by</label><br>
                <div class="bg-white rounded-md">
                    <label class="w-full"><?php echo " " . ($task['task_created_by']); ?></label><br>
                    <label class="w-full bg-white"><?php echo " " . ($task['task_creation_date']); ?></label>
                </div>
            </div>

            <div class="w-3/5 ml-2">
                <label>Task ID: <?php echo $task['task_id']; ?> </label>
                <h1 class="block w-full text-center font-bold text-orange-400 text-2x1"><?php echo strtoupper($task['task_name']); ?></h1>
            </div>

            <div class="w-1/5 ml-2">
                <div class="ml-2 bg-orange-300 rounded-md p-1 text-center">
                    <label>Assigned to</label><br>
                    <label class="block w-full font-bold"><?php echo " " . ($task['task_assigned_to']); ?></label>
                </div>
            </div>
        </div>
        <div class="flex mb-2">
            <label class="border border-gray-300 rounded-md p-2 block w-1/6 "><?php echo $shortenedText . "..."; ?></label>
            <div class="flex ml-2">
                <button class="text-blue-500 ml-2 text-lg scale-100" onclick="toggleModal('task-<?php echo $task['task_id']; ?>')"><i class="fas fa-eye"></i></button>
                <label class="w-2/5 text-center"><strong>Deadline:</strong> <?php echo($task['task_deadline']); ?></label>
                <input class="w-1/5 ml-40 text-center" value="<?php echo($task['task_status']); ?>"></input>
                <button class="text-green-500 ml-20 text-lg scale-125"><i class="fas fa-edit"></i></button>
                <button class="text-red-500 ml-20 text-lg scale-125"><a href="<?php echo WEB_ROOT . "/getViewPreDelete/" . $task['task_id']; ?>"><i class="fas fa-trash"></i></a></button>

            </div>
        </div>
    </div>

<!-- Modal  -->
<div id="task-<?php echo $task['task_id']; ?>" class="modal hidden fixed inset-0 overflow-y-auto z-50">
    <?php include('modalShowOneTask.php'); ?>
</div>
<!-- Fin del modal -->

    <?php endforeach; ?>

<?php else : ?>
    <p>No hay datos a mostrar.</p>
<?php endif; ?>
</div>

<script>

</script>
