<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TO DO LIST</title>
	<link rel="stylesheet" href="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/stylesheets/styles.css">
	<script src="https://cdn.tailwindcss.com"></script>
	<script src="javascripts/functions.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />

</head>

<body class="min-h-screen flex flex-col ">

	<header class="bg-orange-500 p-1 flex items-center justify-between w-full fixed top-0 z-50">
		<!-- Title -->
		<div class="flex-shrink-0 ml-2">
			<a href="<?php echo WEB_ROOT?>">
				<img src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/todolisticon.png" alt="todolist_icon" class="w-15 h-13">
			</a>
		</div>
		<!-- Navigation -->
		<div class="w-3/4 p-2 flex justify-between items-center text-sm">
			<!-- Main action: create task -->
    		<a href="<?php echo WEB_ROOT . "/getinsertform"?>" class="mx-2 bg-lime-300 hover:bg-lime-400 py-2 px-4 rounded"><button>CREATE TASK</button></a>
    		<!-- Search actions -->
			<div class="flex bg-orange-400 p-2 rounded">
				<div class="flex items-center mr-3 ml-2 text-base">Search options</div>
				<a href="#" class="mx-2 bg-white py-2 px-4 rounded"><button>Created by</button></a>
				<a href="#" class="mx-2 bg-white py-2 px-4 rounded"><button>Assigned to</button></a>
				<a href="#" class="mx-2 bg-white py-2 px-4 rounded"><button>Status</button></a>
				<a href="#" class="mx-2 bg-white py-2 px-4 rounded"><button>Start date</button></a>
				<a href="#" class="mx-2 bg-white py-2 px-4 rounded"><button>Deadline</button></a>
			</div>
		</div>
	</header>

	<main class="flex-grow flex flex-col h-full mt-24">
    	<?= $this->content() ?>		
  	</main>

    <footer class="bg-gray-800 text-white p-4 text-center mt-auto">
        <p class="text-white mt-2">App created by</p>
        <div class="flex items-center justify-center mt-2">
            <a href="https://www.linkedin.com/in/carles-ruiz-montejo-tecnico-de-campo-especialista" class="flex items-center text-white text-lg mx-5">
                <img src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/linkedin.png" alt="Enlace 1 Icon" class="w-6 h-6 mr-2">
                Carles Ruiz
            </a>
            <a href="https://www.linkedin.com/in/agonzalezar" class="flex items-center text-white text-lg mx-5">
                <img src="http://<?php echo $_SERVER['HTTP_HOST']."/".WEB_ROOT?>/images/linkedin.png" alt="Enlace 2 Icon" class="w-6 h-6 mr-2">
                Antonio González
            </a>
        </div>
    </footer>


</body>
</html>